// Realistic school content for test data generation

export const DOCUMENT_TITLES = [
  "Student Handbook 2025-2026",
  "Parent-Teacher Conference Schedule",
  "Annual Safety Drill Procedures",
  "School Bus Routes and Timetable",
  "Lunch Menu - Spring Semester",
  "Field Trip Permission Form - Science Museum",
  "After-School Programs Registration",
  "PTA Meeting Minutes - January",
  "Academic Calendar 2025-2026",
  "Uniform Policy Guidelines",
  "Library Book List - Grade 5",
  "Special Education Services Overview",
  "Athletics Department Handbook",
  "Music Program Registration Form",
  "Emergency Contact Information Form",
  "School Improvement Plan 2025",
  "Volunteer Opportunities Guide",
  "Grade 3 Curriculum Overview",
  "Standardized Testing Schedule",
  "School Board Policy Manual",
  "Technology Acceptable Use Policy",
  "Anti-Bullying Policy and Procedures",
  "Report Card Explanation Guide",
  "Gifted and Talented Program Details",
  "Summer Reading List - All Grades",
  "Cafeteria Allergy Information Sheet",
  "Arrival and Dismissal Procedures",
  "Snow Day and Delay Policy",
  "Student Code of Conduct",
  "Health Screening Schedule",
  "Back to School Supply List",
  "Fundraiser Information Packet",
  "Graduation Ceremony Details",
  "Kindergarten Readiness Checklist",
  "STEM Lab Safety Guidelines",
  "School Counseling Services Brochure",
  "Parent Volunteer Background Check Form",
  "Homework Policy by Grade Level",
  "Attendance and Tardiness Policy",
  "Building Renovation Update",
];

export const DOCUMENT_DESCRIPTIONS = [
  "Comprehensive guide covering school rules, expectations, dress code, and academic policies for the current year",
  "Schedule and preparation tips for upcoming parent-teacher conferences across all grade levels",
  "Detailed procedures for fire, tornado, earthquake, and lockdown drills conducted throughout the year",
  "Complete routes, pickup times, and stop locations for all district school buses",
  "Weekly lunch menus including nutritional information and allergen warnings",
  "Permission slip and details for the upcoming Grade 4 field trip to the Natural Science Museum",
  "Registration forms and program descriptions for all after-school activities and clubs",
  "Official minutes from the January PTA meeting including budget updates and event planning",
  "Key dates for the school year including holidays, breaks, teacher workdays, and early dismissals",
  "Complete dress code policy with examples of acceptable and unacceptable attire",
  "Recommended reading list for fifth grade students organized by genre and difficulty",
  "Overview of available special education programs, referral process, and contact information",
  "Rules, schedules, eligibility requirements, and tryout dates for all sports programs",
  "Sign-up form for band, orchestra, and choir programs with instrument rental information",
  "Form to update emergency contact details, medical information, and authorized pickup list",
  "Strategic goals and action items for improving student outcomes and school environment",
  "Complete list of volunteer opportunities with time commitments and sign-up instructions",
  "Grade 3 subjects, learning objectives, and expectations for the academic year",
  "Dates, formats, and preparation tips for state-mandated standardized assessments",
  "Comprehensive policy manual covering governance, academic standards, and administrative procedures",
  "Rules and guidelines for student use of school computers, tablets, and internet access",
  "Definition of bullying, reporting procedures, investigation process, and support resources",
  "Guide explaining grading scales, progress indicators, and how to read your child's report card",
  "Eligibility criteria, application process, and program structure for gifted education",
  "Age-appropriate book recommendations for summer reading across all grade levels",
  "List of common allergens in cafeteria meals and procedures for students with food allergies",
  "Morning arrival and afternoon dismissal procedures including carpool and walker policies",
  "Protocols for weather-related school closures, delays, and early dismissals",
  "Behavioral expectations, progressive discipline steps, and appeal process for students",
  "Schedule for vision, hearing, and other health screenings conducted during the school year",
  "Required and recommended supplies for each grade level for the upcoming school year",
  "Details about current fundraising campaigns including goals, prizes, and participation info",
  "Date, time, location, and guest policies for the end-of-year graduation ceremony",
  "Skills and milestones checklist to help prepare children entering kindergarten",
  "Safety rules and procedures for students using the STEM and science laboratories",
  "Services offered by school counselors including academic support and social-emotional help",
  "Background check form required for all parent volunteers working in school facilities",
  "Expected homework amounts and policies for each grade level including late work rules",
  "Attendance requirements, excused vs. unexcused absences, and chronic tardiness intervention",
  "Updates on the building renovation project including timeline, disruptions, and improvements",
];

export const EVENT_TITLES: Record<string, string[]> = {
  general: [
    "Back to School Night",
    "School Picture Day",
    "Open House",
    "Book Fair",
    "Cultural Heritage Day",
    "Spirit Week Kickoff",
    "Grandparents Day Celebration",
    "Student Appreciation Day",
    "School Carnival",
    "Community Service Day",
  ],
  academic: [
    "Science Fair",
    "Spelling Bee",
    "Math Olympiad",
    "Reading Challenge Awards",
    "Honor Roll Ceremony",
    "STEM Showcase",
    "History Day Presentations",
    "Academic Awards Assembly",
    "National Honor Society Induction",
    "Robotics Competition",
  ],
  sports: [
    "Varsity Football Game",
    "Swimming Championship",
    "Track and Field Day",
    "Basketball Tournament",
    "Soccer Match vs. Riverside",
    "Cross Country Meet",
    "Volleyball Tournament",
    "Wrestling Invitational",
    "Softball Opening Day",
    "Tennis Match vs. Lincoln",
  ],
  arts: [
    "Spring Musical Performance",
    "Art Exhibition Opening",
    "Winter Concert",
    "Band Festival",
    "Drama Club Showcase",
    "Choir Performance",
    "Dance Recital",
    "Student Film Festival",
    "Poetry Reading Night",
    "Photography Exhibition",
  ],
  meeting: [
    "PTA Monthly Meeting",
    "School Board Meeting",
    "Parent Advisory Council",
    "Faculty Meeting",
    "Budget Committee Meeting",
    "Safety Committee Review",
    "Curriculum Planning Session",
    "IEP Team Meeting",
    "Booster Club Meeting",
    "Principal's Coffee Chat",
  ],
  holiday: [
    "Winter Break Begins",
    "Teacher Workday - No School",
    "Presidents Day - No School",
    "Spring Break",
    "Memorial Day - No School",
    "Labor Day - No School",
    "Thanksgiving Break",
    "Martin Luther King Jr. Day",
    "Early Release Day",
    "Last Day of School",
  ],
  other: [
    "Blood Drive",
    "Career Day",
    "College Fair",
    "Fire Drill Practice",
    "Picture Retake Day",
    "Yearbook Distribution",
    "Locker Clean-Out Day",
    "Textbook Return Day",
    "New Student Orientation",
    "Staff Development Day",
  ],
};

export const EVENT_DESCRIPTIONS: Record<string, string[]> = {
  general: [
    "Join us for an evening of classroom visits and meeting your child's teachers",
    "Individual and class photos will be taken. Don't forget to smile!",
    "Tour the school and learn about our programs and extracurricular activities",
    "Browse and purchase books from our annual Scholastic Book Fair in the library",
    "Celebrating the diverse cultures and traditions within our school community",
    "Kick off Spirit Week with themed dress-up days and school pride activities",
    "A special day to invite grandparents and special guests to visit classrooms",
    "Recognizing students for their hard work, kindness, and contributions",
    "Annual school carnival with games, food, and fun for the whole family",
    "Students and families come together for community service projects",
  ],
  academic: [
    "Students present their science projects to judges and the school community",
    "Grade-level and school-wide spelling competitions leading to the district bee",
    "Students compete in math problem-solving challenges across grade levels",
    "Celebrating students who completed the reading challenge this semester",
    "Ceremony recognizing students who achieved Honor Roll or High Honor Roll",
    "Hands-on demonstrations of student STEM projects and innovations",
    "Student presentations on local and national history research projects",
    "Annual assembly recognizing outstanding academic achievement across all grades",
    "Formal induction ceremony for new National Honor Society members",
    "Teams compete using robots they designed and programmed",
  ],
  sports: [
    "Cheer on our varsity football team in this important conference game",
    "District swimming championship at the aquatic center",
    "A day of outdoor athletic events and friendly competition for all students",
    "Multi-day basketball tournament featuring teams from across the district",
    "Home game against Riverside School. Come support our soccer team!",
    "Distance running event at the park course. All spectators welcome",
    "Volleyball teams compete in this round-robin tournament format",
    "Wrestling invitational featuring teams from surrounding schools",
    "Season opener for our softball program. First pitch at 4:00 PM",
    "Varsity tennis home match against Lincoln School",
  ],
  arts: [
    "The drama department presents this year's spring musical production",
    "Student artwork on display in the gallery. Reception with refreshments",
    "Annual winter concert featuring band, orchestra, and choir performances",
    "Our band program participates in the regional band festival competition",
    "Drama club members perform short scenes and monologues",
    "School choir performs seasonal favorites and contemporary pieces",
    "Students showcase choreography learned throughout the semester",
    "Student-produced short films screened in the auditorium",
    "Students share original poetry and creative writing pieces",
    "Student photography displayed throughout the main hallway gallery",
  ],
  meeting: [
    "Monthly PTA meeting to discuss school events, budget, and initiatives",
    "Public school board meeting covering policy updates and budget review",
    "Advisory council discusses parent concerns and school improvement ideas",
    "Staff meeting covering curriculum updates and professional development",
    "Review of the annual budget allocation and expenditure reports",
    "Committee reviews safety protocols, incident reports, and improvements",
    "Teachers collaborate on curriculum alignment and instructional strategies",
    "Individualized Education Program review meeting for special education students",
    "Booster club discusses fundraising and support for athletic programs",
    "Informal meeting with the principal to discuss school topics over coffee",
  ],
  holiday: [
    "Students are dismissed for winter break. Happy holidays!",
    "No school for students. Teachers participate in professional development",
    "School closed in observance of Presidents Day",
    "Students are dismissed for spring break. Enjoy the time off!",
    "School closed in observance of Memorial Day",
    "School closed in observance of Labor Day",
    "Students are dismissed for Thanksgiving break",
    "School closed in observance of Martin Luther King Jr. Day",
    "Students are dismissed early. Check grade-level dismissal times",
    "Congratulations on a great year! See you next fall!",
  ],
  other: [
    "American Red Cross blood drive in the gymnasium. Sign up to donate",
    "Professionals from various fields visit to share about their careers",
    "Representatives from local colleges and universities share admission info",
    "Scheduled fire drill. Please review evacuation procedures with students",
    "Retake photos for students who missed Picture Day or want a retake",
    "Yearbooks will be distributed during homeroom. Extra copies available",
    "Students clean out lockers and return any school property",
    "All textbooks and library books must be returned by end of day",
    "Welcome event for students and families new to the school",
    "No school for students. Staff professional development day",
  ],
};

export const EVENT_LOCATIONS = [
  "Main Auditorium",
  "Gymnasium",
  "Library",
  "Cafeteria",
  "Football Field",
  "Science Lab",
  "Room 204",
  "Conference Room A",
  "Multi-Purpose Room",
  "Art Studio",
  "Music Room",
  "Track Field",
  "Media Center",
  "Front Office",
  "Playground",
  "Baseball Diamond",
  "Tennis Courts",
  "Swimming Pool",
  "Band Room",
  "Theater",
];

export const ANNOUNCEMENT_TITLES: Record<string, string[]> = {
  normal: [
    "Reminder: Picture Day is This Friday",
    "Cafeteria Menu Update for Next Week",
    "Library Book Fair Starting Monday",
    "After-School Club Registration Now Open",
    "Bus Route Change for Route 7",
    "Yearbook Order Deadline Approaching",
    "Volunteer Sign-Up for Spring Festival",
    "New Lunch Payment System Instructions",
    "Report Cards Available in Portal",
    "Summer Program Registration Opens March 1",
  ],
  important: [
    "Schedule Change: Early Dismissal Wednesday",
    "Parent-Teacher Conferences Next Week",
    "New Drop-Off Procedures Effective Monday",
    "Required Health Forms Due by Friday",
    "Updated School Safety Protocols",
    "State Testing Schedule Released",
    "Mandatory Registration for Next Year",
    "Important Changes to Bus Routes",
    "New Attendance Policy Update",
    "Building Access Changes Starting Monday",
  ],
  urgent: [
    "School Closed Tomorrow Due to Weather",
    "Immediate: Water Main Break - Early Dismissal",
    "Emergency Contact Update Required Today",
    "Boil Water Advisory Affecting School",
    "Road Closure Affecting Bus Routes Today",
    "Power Outage - Modified Schedule Today",
    "Severe Weather Alert - Shelter in Place Drill",
    "Immediate Pickup Required - Facility Issue",
    "Critical: Student Safety Alert",
    "Emergency: School Closing Early Today",
  ],
};

export const ANNOUNCEMENT_CONTENT: Record<string, string[]> = {
  normal: [
    "Just a reminder that school picture day is this Friday. Please ensure your child is dressed according to the dress code. Retake day will be scheduled for those who are absent.",
    "Please note the updated cafeteria menu for next week. We've added new vegetarian options on Tuesday and Thursday. Allergen information is available on the school website.",
    "Our annual Scholastic Book Fair begins Monday in the library. Students will visit during their scheduled library time. Family shopping hours are 3:30-5:30 PM daily.",
    "Registration for after-school clubs and activities is now open. Available programs include robotics, art, drama, and coding. Space is limited so sign up early!",
    "Bus Route 7 will be temporarily adjusted starting next Monday due to road construction on Oak Street. Please check the updated route map on our transportation page.",
    "The deadline to order yearbooks is March 15. Orders can be placed online through the school store. The price is $25 for softcover and $35 for hardcover.",
    "We need parent volunteers for the Spring Festival on April 12. Sign up for shifts at the front office or through the volunteer portal online.",
    "We've transitioned to a new online lunch payment system. Please set up your account by Friday. Instructions are attached to this announcement.",
    "First quarter report cards are now available in the parent portal. Please log in to review your child's grades and teacher comments.",
    "Registration for summer enrichment programs opens March 1. Programs available include STEM camp, arts workshop, sports clinics, and academic tutoring.",
  ],
  important: [
    "Please be aware that this Wednesday will be an early dismissal day. Students will be released at 1:00 PM. After-school activities are canceled for the day.",
    "Parent-teacher conferences are scheduled for next Tuesday and Thursday from 4:00-7:00 PM. Please book your time slot through the online scheduling system.",
    "New morning drop-off procedures will take effect Monday. All cars must enter from the south entrance and proceed through the designated lane. Staff will be on hand to direct traffic.",
    "All required health forms including immunization records must be submitted by Friday. Students without completed forms may not attend school starting next Monday.",
    "We have updated our school safety protocols following our annual review. Please read the attached document and discuss emergency procedures with your children.",
    "The state testing schedule has been released for this spring. Tests begin April 7. Please ensure your child gets plenty of rest and arrives on time during testing weeks.",
    "Registration packets for the upcoming school year must be completed by March 31. This applies to all returning and new students.",
    "Several bus routes will be changing effective next Monday due to the new residential development. Check the transportation page for your child's updated route and times.",
    "Our attendance policy has been updated to align with new district guidelines. Key changes include the definition of excused absences and the tardiness threshold.",
    "Building access procedures are changing starting Monday. All visitors must enter through the main entrance and use the new electronic check-in system.",
  ],
  urgent: [
    "Due to forecasted severe winter weather, school will be closed tomorrow. All after-school activities and evening events are also canceled. Stay safe!",
    "A water main break has occurred near the school. For the safety of students, we will be dismissing early at 11:30 AM. Please arrange pickup immediately.",
    "We need all families to verify and update their emergency contact information in the parent portal today. This is critical for student safety.",
    "A boil water advisory has been issued for our area. The school is providing bottled water. Please send water bottles with your children until further notice.",
    "A road closure on Main Street is affecting bus routes 3, 5, and 8 today. Buses may be 15-20 minutes late. We apologize for the inconvenience.",
    "A power outage is affecting parts of the school building. We are operating on a modified schedule today. All afternoon activities are canceled.",
    "A severe weather alert has been issued for our area. We have conducted a shelter-in-place drill and students are safe. Dismissal may be delayed.",
    "Due to a facility issue, we need all students picked up by 1:00 PM today. Please arrange transportation as soon as possible.",
    "We are aware of a safety concern reported in the neighborhood. Extra security measures are in place. All students are safe inside the building.",
    "Due to an emergency facility issue, school is closing early today at 11:00 AM. Buses will run their regular routes early. Please arrange pickup if possible.",
  ],
};

export const CATEGORY_NAMES = [
  "Academic Policies",
  "Student Resources",
  "Parent Information",
  "Health & Safety",
  "Athletics",
  "Arts & Music",
  "Administration",
  "Curriculum",
  "Transportation",
  "Food Services",
  "Technology",
  "Special Education",
  "Enrollment",
  "Community",
  "Facilities",
];

export const CATEGORY_DESCRIPTIONS: Record<string, string> = {
  "Academic Policies": "Grading scales, homework rules, testing standards, and academic integrity policies",
  "Student Resources": "Counseling, tutoring, library resources, and student support services",
  "Parent Information": "Parent guides, volunteer opportunities, and family engagement resources",
  "Health & Safety": "Health screenings, safety drills, wellness policies, and emergency procedures",
  "Athletics": "Sports programs, team schedules, eligibility requirements, and athletic policies",
  "Arts & Music": "Visual arts, performing arts, music programs, and creative activities",
  "Administration": "School policies, board minutes, staff directories, and official communications",
  "Curriculum": "Course descriptions, learning objectives, and instructional materials",
  "Transportation": "Bus routes, schedules, transportation policies, and carpool information",
  "Food Services": "Lunch menus, nutrition information, allergy policies, and meal payment",
  "Technology": "Acceptable use policies, device information, and digital learning resources",
  "Special Education": "IEP processes, accommodations, specialized programs, and support services",
  "Enrollment": "Registration forms, enrollment deadlines, and new student orientation",
  "Community": "Community partnerships, service projects, and neighborhood resources",
  "Facilities": "Building information, renovation updates, and room reservations",
};

export const FOLDER_NAMES = [
  "2025-2026 School Year",
  "Forms & Applications",
  "Newsletters",
  "Meeting Minutes",
  "Policies",
  "Reports",
  "Archives",
];

export const FOLDER_CHILDREN: Record<string, string[]> = {
  "2025-2026 School Year": ["Fall Semester", "Spring Semester", "Summer"],
  "Meeting Minutes": ["PTA", "School Board", "Faculty"],
  "Forms & Applications": ["Enrollment", "Permission Slips", "Health Forms"],
  "Policies": ["Student Policies", "Staff Policies", "Administrative"],
  "Reports": ["Academic Reports", "Financial Reports", "Safety Reports"],
};

export const DOCUMENT_TAGS = [
  "enrollment",
  "safety",
  "curriculum",
  "policies",
  "sports",
  "arts",
  "parent-info",
  "grades",
  "testing",
  "nutrition",
  "transportation",
  "technology",
  "special-education",
  "calendar",
  "forms",
  "volunteer",
  "health",
  "budget",
  "facilities",
  "community",
];

export const COLORS = [
  "#6366f1",
  "#8b5cf6",
  "#ec4899",
  "#ef4444",
  "#f97316",
  "#eab308",
  "#22c55e",
  "#14b8a6",
  "#06b6d4",
  "#3b82f6",
  "#a855f7",
  "#f43f5e",
  "#84cc16",
  "#0ea5e9",
  "#d946ef",
];

// --- Utility functions ---

export function pickRandom<T>(arr: T[]): T {
  return arr[Math.floor(Math.random() * arr.length)];
}

export function pickRandomN<T>(arr: T[], n: number): T[] {
  const shuffled = [...arr].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, Math.min(n, arr.length));
}

/** Returns an ISO date string (YYYY-MM-DD) for a random date between startDays and endDays from now */
export function randomDateInRange(startDays: number, endDays: number): string {
  const now = new Date();
  const offsetDays = startDays + Math.floor(Math.random() * (endDays - startDays));
  const date = new Date(now.getTime() + offsetDays * 86400000);
  return date.toISOString().split("T")[0];
}

/** Returns a time string (HH:MM) between minHour and maxHour */
export function randomTime(minHour: number, maxHour: number): string {
  const hour = minHour + Math.floor(Math.random() * (maxHour - minHour));
  const minute = Math.random() < 0.5 ? "00" : "30";
  return `${hour.toString().padStart(2, "0")}:${minute}`;
}

/** Returns a random integer between min and max (inclusive) */
export function randomInt(min: number, max: number): number {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}
